#!/bin/bash

sudo apt-get install -y libqt5-default

cd
git clone --recursive https://github.com/hyperion-project/hyperion.git

cd hyperion/
mkdir build

cd build
cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_AMLOGIC=ON -DENABLE_FB=ON -DENABLE_QT5=ON -DCMAKE_BUILD_TYPE=Release -Wno-dev ..
make -j4

cd bin
sudo cp * /usr/bin

cd ..
sudo mkdir /usr/share/hyperion
sudo cp -r effects /usr/share/

cp 
To run install 
libqt5core5a libqt5gui5 libqt5widgets5 libqt5network5
